-- 題庫 Seeder
-- 為每個題型生成至少 10 題 easy、10 題 medium、10 題 hard

-- A1: 基礎運算 (3-1)
-- Easy
INSERT INTO questions (chapter_id, type_id, difficulty, qtype, prompt, answer, choices, correct_choice_index, is_active) VALUES
('3-1', 'A1', 'easy', 'input', '解方程式：x + 5 = 10', '5', NULL, NULL, true),
('3-1', 'A1', 'easy', 'input', '解方程式：x - 3 = 7', '10', NULL, NULL, true),
('3-1', 'A1', 'easy', 'input', '解方程式：2x = 8', '4', NULL, NULL, true),
('3-1', 'A1', 'easy', 'input', '解方程式：x ÷ 2 = 5', '10', NULL, NULL, true),
('3-1', 'A1', 'easy', 'input', '解方程式：x + 8 = 15', '7', NULL, NULL, true),
('3-1', 'A1', 'easy', 'input', '解方程式：x - 6 = 4', '10', NULL, NULL, true),
('3-1', 'A1', 'easy', 'input', '解方程式：3x = 12', '4', NULL, NULL, true),
('3-1', 'A1', 'easy', 'input', '解方程式：x ÷ 3 = 4', '12', NULL, NULL, true),
('3-1', 'A1', 'easy', 'input', '解方程式：x + 12 = 20', '8', NULL, NULL, true),
('3-1', 'A1', 'easy', 'input', '解方程式：x - 9 = 1', '10', NULL, NULL, true),
-- Medium
('3-1', 'A1', 'medium', 'input', '解方程式：2x + 3 = 11', '4', NULL, NULL, true),
('3-1', 'A1', 'medium', 'input', '解方程式：3x - 5 = 10', '5', NULL, NULL, true),
('3-1', 'A1', 'medium', 'input', '解方程式：4x + 7 = 23', '4', NULL, NULL, true),
('3-1', 'A1', 'medium', 'input', '解方程式：5x - 8 = 17', '5', NULL, NULL, true),
('3-1', 'A1', 'medium', 'input', '解方程式：2x + 9 = 21', '6', NULL, NULL, true),
('3-1', 'A1', 'medium', 'input', '解方程式：3x - 12 = 6', '6', NULL, NULL, true),
('3-1', 'A1', 'medium', 'input', '解方程式：6x + 4 = 28', '4', NULL, NULL, true),
('3-1', 'A1', 'medium', 'input', '解方程式：7x - 14 = 21', '5', NULL, NULL, true),
('3-1', 'A1', 'medium', 'input', '解方程式：2x + 15 = 31', '8', NULL, NULL, true),
('3-1', 'A1', 'medium', 'input', '解方程式：4x - 13 = 19', '8', NULL, NULL, true),
-- Hard
('3-1', 'A1', 'hard', 'input', '解方程式：3x + 2x - 5 = 20', '5', NULL, NULL, true),
('3-1', 'A1', 'hard', 'input', '解方程式：5x - 3x + 8 = 18', '5', NULL, NULL, true),
('3-1', 'A1', 'hard', 'input', '解方程式：2x + 3x - 7 = 23', '6', NULL, NULL, true),
('3-1', 'A1', 'hard', 'input', '解方程式：4x - 2x + 5 = 21', '8', NULL, NULL, true),
('3-1', 'A1', 'hard', 'input', '解方程式：6x + x - 9 = 26', '5', NULL, NULL, true),
('3-1', 'A1', 'hard', 'input', '解方程式：7x - 4x + 3 = 18', '5', NULL, NULL, true),
('3-1', 'A1', 'hard', 'input', '解方程式：3x + 5x - 12 = 28', '5', NULL, NULL, true),
('3-1', 'A1', 'hard', 'input', '解方程式：8x - 3x + 6 = 31', '5', NULL, NULL, true),
('3-1', 'A1', 'hard', 'input', '解方程式：5x + 2x - 11 = 24', '5', NULL, NULL, true),
('3-1', 'A1', 'hard', 'input', '解方程式：9x - 5x + 4 = 20', '4', NULL, NULL, true);

-- A2: 移項運算 (3-1)
INSERT INTO questions (chapter_id, type_id, difficulty, qtype, prompt, answer, choices, correct_choice_index, is_active) VALUES
('3-1', 'A2', 'easy', 'input', '解方程式：x + 3 = 8', '5', NULL, NULL, true),
('3-1', 'A2', 'easy', 'input', '解方程式：x - 4 = 6', '10', NULL, NULL, true),
('3-1', 'A2', 'easy', 'input', '解方程式：2x = 14', '7', NULL, NULL, true),
('3-1', 'A2', 'easy', 'input', '解方程式：x ÷ 4 = 3', '12', NULL, NULL, true),
('3-1', 'A2', 'easy', 'input', '解方程式：x + 7 = 12', '5', NULL, NULL, true),
('3-1', 'A2', 'easy', 'input', '解方程式：x - 5 = 8', '13', NULL, NULL, true),
('3-1', 'A2', 'easy', 'input', '解方程式：3x = 18', '6', NULL, NULL, true),
('3-1', 'A2', 'easy', 'input', '解方程式：x ÷ 5 = 2', '10', NULL, NULL, true),
('3-1', 'A2', 'easy', 'input', '解方程式：x + 9 = 16', '7', NULL, NULL, true),
('3-1', 'A2', 'easy', 'input', '解方程式：x - 11 = 4', '15', NULL, NULL, true),
('3-1', 'A2', 'medium', 'input', '解方程式：2x + 4 = 14', '5', NULL, NULL, true),
('3-1', 'A2', 'medium', 'input', '解方程式：3x - 6 = 12', '6', NULL, NULL, true),
('3-1', 'A2', 'medium', 'input', '解方程式：4x + 5 = 25', '5', NULL, NULL, true),
('3-1', 'A2', 'medium', 'input', '解方程式：5x - 10 = 15', '5', NULL, NULL, true),
('3-1', 'A2', 'medium', 'input', '解方程式：2x + 8 = 20', '6', NULL, NULL, true),
('3-1', 'A2', 'medium', 'input', '解方程式：3x - 9 = 9', '6', NULL, NULL, true),
('3-1', 'A2', 'medium', 'input', '解方程式：6x + 3 = 27', '4', NULL, NULL, true),
('3-1', 'A2', 'medium', 'input', '解方程式：7x - 7 = 28', '5', NULL, NULL, true),
('3-1', 'A2', 'medium', 'input', '解方程式：2x + 12 = 28', '8', NULL, NULL, true),
('3-1', 'A2', 'medium', 'input', '解方程式：4x - 16 = 8', '6', NULL, NULL, true),
('3-1', 'A2', 'hard', 'input', '解方程式：3x + 2x = 25', '5', NULL, NULL, true),
('3-1', 'A2', 'hard', 'input', '解方程式：5x - 2x = 18', '6', NULL, NULL, true),
('3-1', 'A2', 'hard', 'input', '解方程式：4x + 3x = 35', '5', NULL, NULL, true),
('3-1', 'A2', 'hard', 'input', '解方程式：6x - 3x = 21', '7', NULL, NULL, true),
('3-1', 'A2', 'hard', 'input', '解方程式：7x + x = 32', '4', NULL, NULL, true),
('3-1', 'A2', 'hard', 'input', '解方程式：8x - 4x = 20', '5', NULL, NULL, true),
('3-1', 'A2', 'hard', 'input', '解方程式：9x + 2x = 44', '4', NULL, NULL, true),
('3-1', 'A2', 'hard', 'input', '解方程式：10x - 5x = 25', '5', NULL, NULL, true),
('3-1', 'A2', 'hard', 'input', '解方程式：3x + 4x = 28', '4', NULL, NULL, true),
('3-1', 'A2', 'hard', 'input', '解方程式：11x - 6x = 25', '5', NULL, NULL, true);

-- E: 標準型 (3-2)
INSERT INTO questions (chapter_id, type_id, difficulty, qtype, prompt, answer, choices, correct_choice_index, is_active) VALUES
('3-2', 'E', 'easy', 'input', '解方程式：x + 2 = 7', '5', NULL, NULL, true),
('3-2', 'E', 'easy', 'input', '解方程式：x - 3 = 5', '8', NULL, NULL, true),
('3-2', 'E', 'easy', 'input', '解方程式：2x = 10', '5', NULL, NULL, true),
('3-2', 'E', 'easy', 'input', '解方程式：x + 4 = 9', '5', NULL, NULL, true),
('3-2', 'E', 'easy', 'input', '解方程式：x - 5 = 3', '8', NULL, NULL, true),
('3-2', 'E', 'easy', 'input', '解方程式：3x = 15', '5', NULL, NULL, true),
('3-2', 'E', 'easy', 'input', '解方程式：x + 6 = 11', '5', NULL, NULL, true),
('3-2', 'E', 'easy', 'input', '解方程式：x - 7 = 2', '9', NULL, NULL, true),
('3-2', 'E', 'easy', 'input', '解方程式：4x = 20', '5', NULL, NULL, true),
('3-2', 'E', 'easy', 'input', '解方程式：x + 8 = 13', '5', NULL, NULL, true),
('3-2', 'E', 'medium', 'input', '解方程式：2x + 3 = 13', '5', NULL, NULL, true),
('3-2', 'E', 'medium', 'input', '解方程式：3x - 4 = 11', '5', NULL, NULL, true),
('3-2', 'E', 'medium', 'input', '解方程式：4x + 5 = 21', '4', NULL, NULL, true),
('3-2', 'E', 'medium', 'input', '解方程式：5x - 6 = 19', '5', NULL, NULL, true),
('3-2', 'E', 'medium', 'input', '解方程式：2x + 7 = 19', '6', NULL, NULL, true),
('3-2', 'E', 'medium', 'input', '解方程式：3x - 8 = 13', '7', NULL, NULL, true),
('3-2', 'E', 'medium', 'input', '解方程式：6x + 2 = 26', '4', NULL, NULL, true),
('3-2', 'E', 'medium', 'input', '解方程式：7x - 3 = 25', '4', NULL, NULL, true),
('3-2', 'E', 'medium', 'input', '解方程式：2x + 9 = 23', '7', NULL, NULL, true),
('3-2', 'E', 'medium', 'input', '解方程式：4x - 7 = 17', '6', NULL, NULL, true),
('3-2', 'E', 'hard', 'input', '解方程式：3x + 2x - 1 = 24', '5', NULL, NULL, true),
('3-2', 'E', 'hard', 'input', '解方程式：5x - 3x + 4 = 18', '7', NULL, NULL, true),
('3-2', 'E', 'hard', 'input', '解方程式：4x + 3x - 5 = 30', '5', NULL, NULL, true),
('3-2', 'E', 'hard', 'input', '解方程式：6x - 2x + 3 = 27', '6', NULL, NULL, true),
('3-2', 'E', 'hard', 'input', '解方程式：7x + x - 6 = 34', '5', NULL, NULL, true),
('3-2', 'E', 'hard', 'input', '解方程式：8x - 4x + 2 = 22', '5', NULL, NULL, true),
('3-2', 'E', 'hard', 'input', '解方程式：9x + 2x - 8 = 36', '4', NULL, NULL, true),
('3-2', 'E', 'hard', 'input', '解方程式：10x - 5x + 1 = 26', '5', NULL, NULL, true),
('3-2', 'E', 'hard', 'input', '解方程式：5x + 3x - 4 = 28', '4', NULL, NULL, true),
('3-2', 'E', 'hard', 'input', '解方程式：11x - 6x + 5 = 30', '5', NULL, NULL, true);

-- EPLUS: 進階型 (3-2)
INSERT INTO questions (chapter_id, type_id, difficulty, qtype, prompt, answer, choices, correct_choice_index, is_active) VALUES
('3-2', 'EPLUS', 'easy', 'input', '解方程式：2x + 1 = 9', '4', NULL, NULL, true),
('3-2', 'EPLUS', 'easy', 'input', '解方程式：3x - 2 = 10', '4', NULL, NULL, true),
('3-2', 'EPLUS', 'easy', 'input', '解方程式：4x + 3 = 19', '4', NULL, NULL, true),
('3-2', 'EPLUS', 'easy', 'input', '解方程式：5x - 4 = 16', '4', NULL, NULL, true),
('3-2', 'EPLUS', 'easy', 'input', '解方程式：2x + 5 = 13', '4', NULL, NULL, true),
('3-2', 'EPLUS', 'easy', 'input', '解方程式：3x - 6 = 6', '4', NULL, NULL, true),
('3-2', 'EPLUS', 'easy', 'input', '解方程式：6x + 2 = 26', '4', NULL, NULL, true),
('3-2', 'EPLUS', 'easy', 'input', '解方程式：7x - 3 = 25', '4', NULL, NULL, true),
('3-2', 'EPLUS', 'easy', 'input', '解方程式：2x + 7 = 15', '4', NULL, NULL, true),
('3-2', 'EPLUS', 'easy', 'input', '解方程式：4x - 8 = 8', '4', NULL, NULL, true),
('3-2', 'EPLUS', 'medium', 'input', '解方程式：2x + 3x = 25', '5', NULL, NULL, true),
('3-2', 'EPLUS', 'medium', 'input', '解方程式：4x - 2x = 14', '7', NULL, NULL, true),
('3-2', 'EPLUS', 'medium', 'input', '解方程式：3x + 5x = 32', '4', NULL, NULL, true),
('3-2', 'EPLUS', 'medium', 'input', '解方程式：6x - 3x = 18', '6', NULL, NULL, true),
('3-2', 'EPLUS', 'medium', 'input', '解方程式：5x + 2x = 28', '4', NULL, NULL, true),
('3-2', 'EPLUS', 'medium', 'input', '解方程式：7x - 4x = 15', '5', NULL, NULL, true),
('3-2', 'EPLUS', 'medium', 'input', '解方程式：8x + x = 36', '4', NULL, NULL, true),
('3-2', 'EPLUS', 'medium', 'input', '解方程式：9x - 5x = 20', '5', NULL, NULL, true),
('3-2', 'EPLUS', 'medium', 'input', '解方程式：3x + 4x = 28', '4', NULL, NULL, true),
('3-2', 'EPLUS', 'medium', 'input', '解方程式：10x - 6x = 24', '6', NULL, NULL, true),
('3-2', 'EPLUS', 'hard', 'input', '解方程式：2x + 3x - 4 = 21', '5', NULL, NULL, true),
('3-2', 'EPLUS', 'hard', 'input', '解方程式：5x - 2x + 3 = 18', '5', NULL, NULL, true),
('3-2', 'EPLUS', 'hard', 'input', '解方程式：4x + 3x - 5 = 23', '4', NULL, NULL, true),
('3-2', 'EPLUS', 'hard', 'input', '解方程式：6x - 3x + 2 = 17', '5', NULL, NULL, true),
('3-2', 'EPLUS', 'hard', 'input', '解方程式：7x + 2x - 6 = 30', '4', NULL, NULL, true),
('3-2', 'EPLUS', 'hard', 'input', '解方程式：8x - 4x + 1 = 21', '5', NULL, NULL, true),
('3-2', 'EPLUS', 'hard', 'input', '解方程式：9x + x - 8 = 32', '4', NULL, NULL, true),
('3-2', 'EPLUS', 'hard', 'input', '解方程式：10x - 5x + 4 = 29', '5', NULL, NULL, true),
('3-2', 'EPLUS', 'hard', 'input', '解方程式：3x + 5x - 7 = 25', '4', NULL, NULL, true),
('3-2', 'EPLUS', 'hard', 'input', '解方程式：11x - 6x + 3 = 28', '5', NULL, NULL, true);

-- F: 分數型 (3-2)
INSERT INTO questions (chapter_id, type_id, difficulty, qtype, prompt, answer, choices, correct_choice_index, is_active) VALUES
('3-2', 'F', 'easy', 'input', '解方程式：(x/2) = 5', '10', NULL, NULL, true),
('3-2', 'F', 'easy', 'input', '解方程式：(x/3) = 4', '12', NULL, NULL, true),
('3-2', 'F', 'easy', 'input', '解方程式：(x/4) = 3', '12', NULL, NULL, true),
('3-2', 'F', 'easy', 'input', '解方程式：(x/5) = 2', '10', NULL, NULL, true),
('3-2', 'F', 'easy', 'input', '解方程式：(x/2) = 6', '12', NULL, NULL, true),
('3-2', 'F', 'easy', 'input', '解方程式：(x/3) = 5', '15', NULL, NULL, true),
('3-2', 'F', 'easy', 'input', '解方程式：(x/4) = 4', '16', NULL, NULL, true),
('3-2', 'F', 'easy', 'input', '解方程式：(x/5) = 3', '15', NULL, NULL, true),
('3-2', 'F', 'easy', 'input', '解方程式：(x/2) = 7', '14', NULL, NULL, true),
('3-2', 'F', 'easy', 'input', '解方程式：(x/3) = 6', '18', NULL, NULL, true),
('3-2', 'F', 'medium', 'input', '解方程式：(x/2) + 3 = 8', '10', NULL, NULL, true),
('3-2', 'F', 'medium', 'input', '解方程式：(x/3) - 2 = 4', '18', NULL, NULL, true),
('3-2', 'F', 'medium', 'input', '解方程式：(x/4) + 5 = 10', '20', NULL, NULL, true),
('3-2', 'F', 'medium', 'input', '解方程式：(x/5) - 1 = 3', '20', NULL, NULL, true),
('3-2', 'F', 'medium', 'input', '解方程式：(x/2) + 4 = 11', '14', NULL, NULL, true),
('3-2', 'F', 'medium', 'input', '解方程式：(x/3) - 3 = 5', '24', NULL, NULL, true),
('3-2', 'F', 'medium', 'input', '解方程式：(x/4) + 6 = 12', '24', NULL, NULL, true),
('3-2', 'F', 'medium', 'input', '解方程式：(x/5) - 2 = 4', '30', NULL, NULL, true),
('3-2', 'F', 'medium', 'input', '解方程式：(x/2) + 5 = 13', '16', NULL, NULL, true),
('3-2', 'F', 'medium', 'input', '解方程式：(x/3) - 4 = 6', '30', NULL, NULL, true),
('3-2', 'F', 'hard', 'input', '解方程式：(x/2) + (x/3) = 10', '12', NULL, NULL, true),
('3-2', 'F', 'hard', 'input', '解方程式：(x/3) - (x/4) = 2', '24', NULL, NULL, true),
('3-2', 'F', 'hard', 'input', '解方程式：(x/4) + (x/5) = 9', '20', NULL, NULL, true),
('3-2', 'F', 'hard', 'input', '解方程式：(x/2) - (x/5) = 6', '20', NULL, NULL, true),
('3-2', 'F', 'hard', 'input', '解方程式：(x/3) + (x/6) = 8', '16', NULL, NULL, true),
('3-2', 'F', 'hard', 'input', '解方程式：(x/4) - (x/6) = 3', '36', NULL, NULL, true),
('3-2', 'F', 'hard', 'input', '解方程式：(x/5) + (x/10) = 6', '20', NULL, NULL, true),
('3-2', 'F', 'hard', 'input', '解方程式：(x/2) - (x/3) = 4', '24', NULL, NULL, true),
('3-2', 'F', 'hard', 'input', '解方程式：(x/3) + (x/4) = 14', '24', NULL, NULL, true),
('3-2', 'F', 'hard', 'input', '解方程式：(x/5) - (x/10) = 2', '20', NULL, NULL, true);

-- W1: 應用題型一 (3-3)
INSERT INTO questions (chapter_id, type_id, difficulty, qtype, prompt, answer, equation, is_active) VALUES
('3-3', 'W1', 'easy', 'word', '小明有 20 元，買了 x 元的糖果後，還剩下 8 元。請問 x 是多少？', '12', '20 - x = 8', true),
('3-3', 'W1', 'easy', 'word', '一包餅乾有 15 片，吃了 x 片後，還剩下 9 片。請問 x 是多少？', '6', '15 - x = 9', true),
('3-3', 'W1', 'easy', 'word', '書架上有 25 本書，借出 x 本後，還剩下 18 本。請問 x 是多少？', '7', '25 - x = 18', true),
('3-3', 'W1', 'easy', 'word', '小華有 30 顆彈珠，送給朋友 x 顆後，還剩下 22 顆。請問 x 是多少？', '8', '30 - x = 22', true),
('3-3', 'W1', 'easy', 'word', '一盒鉛筆有 24 支，用掉 x 支後，還剩下 16 支。請問 x 是多少？', '8', '24 - x = 16', true),
('3-3', 'W1', 'easy', 'word', '停車場有 40 個車位，停了 x 輛車後，還剩下 32 個空位。請問 x 是多少？', '8', '40 - x = 32', true),
('3-3', 'W1', 'easy', 'word', '一袋米有 50 公斤，用掉 x 公斤後，還剩下 35 公斤。請問 x 是多少？', '15', '50 - x = 35', true),
('3-3', 'W1', 'easy', 'word', '教室裡有 35 個座位，坐了 x 個學生後，還剩下 28 個空位。請問 x 是多少？', '7', '35 - x = 28', true),
('3-3', 'W1', 'easy', 'word', '一箱蘋果有 60 顆，賣出 x 顆後，還剩下 45 顆。請問 x 是多少？', '15', '60 - x = 45', true),
('3-3', 'W1', 'easy', 'word', '水桶裡有 80 公升水，倒出 x 公升後，還剩下 65 公升。請問 x 是多少？', '15', '80 - x = 65', true),
('3-3', 'W1', 'medium', 'word', '小美買了 3 支筆，每支 x 元，總共花了 45 元。請問每支筆多少元？', '15', '3x = 45', true),
('3-3', 'W1', 'medium', 'word', '一盒巧克力有 x 顆，分成 4 包，每包 12 顆。請問一盒有幾顆？', '48', 'x / 4 = 12', true),
('3-3', 'W1', 'medium', 'word', '小明每天存 x 元，存了 5 天後，總共有 100 元。請問每天存多少元？', '20', '5x = 100', true),
('3-3', 'W1', 'medium', 'word', '一輛公車載了 x 人，到站後下車 8 人，還剩下 32 人。請問原本有幾人？', '40', 'x - 8 = 32', true),
('3-3', 'W1', 'medium', 'word', '一包糖果有 x 顆，吃了 15 顆後，還剩下 25 顆。請問原本有幾顆？', '40', 'x - 15 = 25', true),
('3-3', 'W1', 'medium', 'word', '小華有 x 元，買了 2 本書，每本 18 元，還剩下 14 元。請問原本有多少元？', '50', 'x - 36 = 14', true),
('3-3', 'W1', 'medium', 'word', '一箱水果有 x 公斤，賣出 20 公斤後，還剩下 30 公斤。請問原本有幾公斤？', '50', 'x - 20 = 30', true),
('3-3', 'W1', 'medium', 'word', '小美每天走 x 公里，走了 6 天，總共走了 42 公里。請問每天走幾公里？', '7', '6x = 42', true),
('3-3', 'W1', 'medium', 'word', '一盒餅乾有 x 片，分成 5 包，每包 10 片。請問一盒有幾片？', '50', 'x / 5 = 10', true),
('3-3', 'W1', 'medium', 'word', '小明買了 4 個麵包，每個 x 元，總共花了 60 元。請問每個麵包多少元？', '15', '4x = 60', true),
('3-3', 'W1', 'hard', 'word', '小華有 x 元，買了 3 支筆（每支 12 元）和 2 本書（每本 15 元），還剩下 8 元。請問原本有多少元？', '74', 'x - 36 - 30 = 8', true),
('3-3', 'W1', 'hard', 'word', '一箱蘋果有 x 顆，第一天賣出 20 顆，第二天賣出 15 顆，還剩下 25 顆。請問原本有幾顆？', '60', 'x - 20 - 15 = 25', true),
('3-3', 'W1', 'hard', 'word', '小明每天存 x 元，存了 7 天後，又存了 50 元，總共有 120 元。請問每天存多少元？', '10', '7x + 50 = 120', true),
('3-3', 'W1', 'hard', 'word', '一包米有 x 公斤，用掉 15 公斤煮飯，用掉 10 公斤做點心，還剩下 25 公斤。請問原本有幾公斤？', '50', 'x - 15 - 10 = 25', true),
('3-3', 'W1', 'hard', 'word', '小美買了 5 支筆（每支 x 元）和 3 本書（每本 20 元），總共花了 95 元。請問每支筆多少元？', '7', '5x + 60 = 95', true),
('3-3', 'W1', 'hard', 'word', '一箱水果有 x 公斤，第一天賣出 25 公斤，第二天賣出 20 公斤，還剩下 15 公斤。請問原本有幾公斤？', '60', 'x - 25 - 20 = 15', true),
('3-3', 'W1', 'hard', 'word', '小華每天走 x 公里，走了 8 天後，又走了 16 公里，總共走了 72 公里。請問每天走幾公里？', '7', '8x + 16 = 72', true),
('3-3', 'W1', 'hard', 'word', '一盒餅乾有 x 片，分成 6 包，每包 12 片，還剩下 8 片。請問一盒有幾片？', '80', 'x - 72 = 8', true),
('3-3', 'W1', 'hard', 'word', '小明買了 6 個麵包（每個 x 元）和 2 瓶飲料（每瓶 15 元），總共花了 90 元。請問每個麵包多少元？', '10', '6x + 30 = 90', true),
('3-3', 'W1', 'hard', 'word', '一箱蘋果有 x 顆，第一天賣出 30 顆，第二天賣出 25 顆，還剩下 20 顆。請問原本有幾顆？', '75', 'x - 30 - 25 = 20', true);

-- W2, W3 簡化生成（類似結構）
-- 這裡只生成部分，實際可依需求擴充
INSERT INTO questions (chapter_id, type_id, difficulty, qtype, prompt, answer, equation, is_active) VALUES
('3-3', 'W2', 'easy', 'word', '小明的年齡是 x 歲，3 年後是 15 歲。請問小明現在幾歲？', '12', 'x + 3 = 15', true),
('3-3', 'W2', 'easy', 'word', '一輛車時速 x 公里，行駛 2 小時，總共行駛 120 公里。請問時速多少？', '60', '2x = 120', true),
('3-3', 'W3', 'easy', 'word', '一個數 x 的 3 倍是 24。請問這個數是多少？', '8', '3x = 24', true);

